spring:
  mail:
    host: smtp.qq.com
    username: 1048791780@qq.com
    password: lgwzdolylfznbeah
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
lagou:
  mail:
    content:
      verifyCode:
        topic: 拉勾教育注册邮件通知2
        content: <h1>欢迎注册拉勾教育，您的注册验证码为：{{verifyCode}}, 祝您学习愉快!</h1>
